### ISSUE TITLE
Nearest Neighbors

### ISSUE THREAD

**Issue by genomeboy** [althonos/mini3di#1]
Thanks for this, very handy!

I was wondering whether it is possible to export/print, for each residue in a chain, the site (number) of the residue that was selected for the nearest neighbor to the virtual center in the 3Di state assignment? If this can already be done, can you let me know how? if not, is it possible to introduce such a feature?

Many thanks

**Comment by genomeboy** [comment]
Hi there,
Actually, no worries, I have done a little mod and exported the relevant array. 
Best wishes
David

**Comment by althonos** [comment]
Hi David,
I have added an encoder class to do that, you can use the `PartnerIndexEncoder` to get the neighbor indices.
